#!/bin/bash
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=03:00:00
#SBATCH --mem=50G
#SBATCH -J Enrichment_KER_Glycogen_PreDepl
#SBATCH -o Enrichment_KER_Glycogen_PreDepl.o%j

#=====================================================================
# This script runs: Enrichment_KER_Glycogen_PreDepl.R
# Submited on: Tue Oct 30 15:36:10 EDT 2018
#=====================================================================

# Work Directory
cd /mnt/research/NMDL/KER_Glycogen_and_RER_Thoroughbred/RNA_Seq/Enrichment/Enrichment_KER_Glycogen_PreDepl

# Run R Code
R -e 'library("knitr");knitr::spin ("Enrichment_KER_Glycogen_PreDepl.R")'

# Add metadata to md file
cat .metadata Enrichment_KER_Glycogen_PreDepl.md > tmp; mv tmp Enrichment_KER_Glycogen_PreDepl.md

# Render HTML
R -e 'library("prettydoc");rmarkdown::render ("Enrichment_KER_Glycogen_PreDepl.md")'

# Job Details
echo Job Details
scontrol show job $SLURM_JOB_ID
