#!/bin/bash
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=03:00:00
#SBATCH --mem=10G
#SBATCH -J DE_KER_Glycogen
#SBATCH -o DE_KER_Glycogen.o%j

#=====================================================================
# This script runs: DE_KER_Glycogen.R
# Submited on: Thu Oct 25 09:08:17 EDT 2018
#=====================================================================

# Work Directory
cd /mnt/research/NMDL/KER_Glycogen_and_RER_Thoroughbred/RNA_Seq/DE/DE_KER_Glycogen

# Run R Code
R -e 'library("knitr");knitr::spin ("DE_KER_Glycogen.R")'

# Add metadata to md file
cat .metadata DE_KER_Glycogen.md > tmp; mv tmp DE_KER_Glycogen.md

# Render HTML
R -e 'library("prettydoc");rmarkdown::render ("DE_KER_Glycogen.md")'

# Job Details
echo Job Details
scontrol show job $SLURM_JOB_ID
